import {
  Calendar,
  Gamepad2,
  Link,
  ShoppingBag,
  Bot,
  Coins,
  Shield,
  SlidersHorizontal,
  Terminal,
  Timer,
  ShieldCheck,
  Braces,
  LayoutDashboard,
  Settings,
  TrendingUp,
  Trophy,
  Users,
  Package,
  Folder,
  Receipt,
  Settings2,
  LayoutTemplate,
  Palette,
  LayoutGrid,
  Link2,
  BarChart3,
  Smile,
  Monitor,
  Sparkles,
  ExternalLink,
  Home,
  type LucideIcon,
} from "lucide-react";

const PANEL_ICON_MAP: Record<string, LucideIcon> = {
  calendar: Calendar,
  "gamepad-2": Gamepad2,
  link: Link,
  "shopping-bag": ShoppingBag,
  bot: Bot,
  coins: Coins,
  shield: Shield,
  "sliders-horizontal": SlidersHorizontal,
  terminal: Terminal,
  timer: Timer,
  "shield-check": ShieldCheck,
  braces: Braces,
  "layout-dashboard": LayoutDashboard,
  settings: Settings,
  "trending-up": TrendingUp,
  trophy: Trophy,
  users: Users,
  package: Package,
  folder: Folder,
  receipt: Receipt,
  "settings-2": Settings2,
  "layout-template": LayoutTemplate,
  palette: Palette,
  "layout-grid": LayoutGrid,
  "link-2": Link2,
  "bar-chart-3": BarChart3,
  smile: Smile,
  monitor: Monitor,
  sparkles: Sparkles,
  "external-link": ExternalLink,
  home: Home,
};

export function getPanelFeatureIcon(iconName: string): LucideIcon {
  return PANEL_ICON_MAP[iconName] ?? LayoutDashboard;
}
